<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_664e26e56d06e',
	'title' => 'Components',
	'fields' => array(
		array(
			'key' => 'field_664e26e508e2c',
			'label' => 'Components',
			'name' => 'components',
			'aria-label' => '',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_flexible_advanced' => 0,
			'layouts' => array(
				'layout_66e1d5e75b235' => array(
					'key' => 'layout_66e1d5e75b235',
					'name' => 'slides',
					'label' => 'Slides',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_66e1d5ed5b238',
							'label' => 'Module: Slides',
							'name' => 'module-slides',
							'aria-label' => '',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_66e1d531c843e',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_seamless_style' => 0,
							'acfe_clone_modal' => 0,
							'acfe_clone_modal_close' => 0,
							'acfe_clone_modal_button' => '',
							'acfe_clone_modal_size' => 'large',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
				),
				'layout_6654e4ecb284d' => array(
					'key' => 'layout_6654e4ecb284d',
					'name' => 'hero',
					'label' => 'Hero',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_6654e501b284f',
							'label' => 'Module: Hero',
							'name' => 'module-hero',
							'aria-label' => '',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_669a7fb78dd6b',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_seamless_style' => 0,
							'acfe_clone_modal' => 0,
							'acfe_clone_modal_close' => 0,
							'acfe_clone_modal_button' => '',
							'acfe_clone_modal_size' => 'large',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
				),
				'layout_6654f7dba7540' => array(
					'key' => 'layout_6654f7dba7540',
					'name' => 'title',
					'label' => 'Title',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_6654f7eb1c86a',
							'label' => 'Title',
							'name' => 'title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '60',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_6654fcbc9e650',
							'label' => 'Theme',
							'name' => 'theme',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'small' => 'Small',
								'large' => 'Large',
								'large-menu' => 'Large w/ Menu',
							),
							'default_value' => 'small',
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'allow_custom' => 0,
							'search_placeholder' => '',
						),
						array(
							'key' => 'field_6654f8031c86b',
							'label' => 'Color Scheme',
							'name' => 'color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'red' => 'Red',
								'tan' => 'Tan',
							),
							'default_value' => 'red',
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'allow_custom' => 0,
							'search_placeholder' => '',
						),
						array(
							'key' => 'field_6685474034259',
							'label' => 'Section Menu',
							'name' => 'nav-menu',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								0 => '- no menu -',
								'about-engage' => 'About - Engage',
								'about-history' => 'About - History',
								'about-main' => 'About - Main',
								'about-support' => 'About - Support',
								'academics-experiential-learning' => 'Academics - Experiential Learning',
								'academics-library' => 'Academics - Library',
								'academics-overview' => 'Academics - Overview',
								'academics-registrar' => 'Academics - Registrar',
								'admission-accepted-students' => 'Admission - Accepted Students',
								'admission-apply' => 'Admission - Apply',
								'admission-financial-aid' => 'Admission - Financial Aid',
								'admission-overview' => 'Admission - Overview',
								'admission-visit' => 'Admission - Visit',
								'apply-now' => 'Apply Now',
								'areas-of-study-nav' => 'Areas of Study Nav',
								'centers-and-resources' => 'Centers and Resources',
								'community-resources' => 'Community Resources',
								'donors' => 'Donors',
								'financial-aid-short' => 'Financial Aid Short',
								'footer-faculty' => 'Footer - Faculty',
								'footer-overview' => 'Footer - Overview',
								'footer-students' => 'Footer - Students',
								'for-parents' => 'for parents',
								'give-forever-ripon' => 'Give - Forever Ripon',
								'give-how-to-give' => 'Give - How to Give',
								'give-infrastructure' => 'Give - Infrastructure',
								'header-main' => 'Header - Main',
								'home-passions' => 'Home - Passions',
								'impact-of-giving' => 'Impact of Giving',
								'international-students' => 'International Students',
								'maps' => 'Maps',
								'news-and-events' => 'News and Events',
								'student-life-club-activities' => 'Student Life - Club &amp; Activities',
								'student-life-diversity-inclusion' => 'Student Life - Diversity &amp; Inclusion',
								'student-life-housing' => 'Student Life - Housing',
								'student-life-main' => 'Student Life - Main',
								'student-life-overview' => 'Student Life - Overview',
								'student-life-services' => 'Student Life - Services',
								'title-academics' => 'Title - Academics',
								'transfer-to-ripon' => 'Transfer To Ripon',
								'where-to-give' => 'Where to GIve',
							),
							'default_value' => false,
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'allow_custom' => 0,
							'search_placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
				),
				'layout_66b4e595fb65e' => array(
					'key' => 'layout_66b4e595fb65e',
					'name' => 'section-title',
					'label' => 'Section Title',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_66b4e5a4fb660',
							'label' => 'Module: Section Title',
							'name' => 'module-section-title',
							'aria-label' => '',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_66b4e515077b0',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_seamless_style' => 0,
							'acfe_clone_modal' => 0,
							'acfe_clone_modal_close' => 0,
							'acfe_clone_modal_button' => '',
							'acfe_clone_modal_size' => 'large',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
				),
				'layout_664e27c208e2e' => array(
					'key' => 'layout_664e27c208e2e',
					'name' => 'content-one',
					'label' => 'Content (1-column)',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_6699b4c45c53c',
							'label' => 'Module: Content (1-column)',
							'name' => 'module-one-column',
							'aria-label' => '',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_6699b1be5fe5e',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_seamless_style' => 0,
							'acfe_clone_modal' => 0,
							'acfe_clone_modal_close' => 0,
							'acfe_clone_modal_button' => '',
							'acfe_clone_modal_size' => 'large',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
				),
				'layout_665512f5602e4' => array(
					'key' => 'layout_665512f5602e4',
					'name' => 'content-two',
					'label' => 'Content (2-column)',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_6699b7f0293d4',
							'label' => 'Module: Content (2-column)',
							'name' => 'modules-two-column',
							'aria-label' => '',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_6699ac4b2da9a',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_seamless_style' => 0,
							'acfe_clone_modal' => 0,
							'acfe_clone_modal_close' => 0,
							'acfe_clone_modal_button' => '',
							'acfe_clone_modal_size' => 'large',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
				),
				'layout_665512f6602eb' => array(
					'key' => 'layout_665512f6602eb',
					'name' => 'content-three',
					'label' => 'Content (3-column)',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_66eb1fcd4824b',
							'label' => 'Module: 3-column',
							'name' => 'module-3-column',
							'aria-label' => '',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_66eb1f49a5ec1',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_seamless_style' => 0,
							'acfe_clone_modal' => 0,
							'acfe_clone_modal_close' => 0,
							'acfe_clone_modal_button' => '',
							'acfe_clone_modal_size' => 'large',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
				),
				'layout_66d86c104d891' => array(
					'key' => 'layout_66d86c104d891',
					'name' => 'areas',
					'label' => 'Areas of Study',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_66d86c174d894',
							'label' => 'Module: Areas of Study',
							'name' => 'module-areas-of-study',
							'aria-label' => '',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_66d86b037558a',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_seamless_style' => 0,
							'acfe_clone_modal' => 0,
							'acfe_clone_modal_close' => 0,
							'acfe_clone_modal_button' => '',
							'acfe_clone_modal_size' => 'large',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
				),
				'layout_66b4ec08112b4' => array(
					'key' => 'layout_66b4ec08112b4',
					'name' => 'cta',
					'label' => 'Calls to Action',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_67093b3179024',
							'label' => '(Column 4/12)',
							'name' => '',
							'aria-label' => '',
							'type' => 'acfe_column',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'columns' => '4/12',
							'endpoint' => 0,
							'allow_in_bindings' => 0,
						),
						array(
							'key' => 'field_66bf9ceee7291',
							'label' => 'Title',
							'name' => 'title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 1,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_66bf9cf7e7292',
							'label' => 'Padding',
							'name' => 'padding',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'pad-normal' => 'Normal',
								'pad-tall' => 'Tall',
							),
							'default_value' => 'normal',
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 1,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'allow_custom' => 0,
							'search_placeholder' => '',
						),
						array(
							'key' => 'field_66cf654c58593',
							'label' => 'Color',
							'name' => 'color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'tan' => 'Tan',
								'white' => 'White',
								'red' => 'Red',
								'image' => 'Background Photo',
								'image-box' => 'Background Photo w/ Red Content Box',
							),
							'default_value' => 'white',
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 1,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'allow_custom' => 0,
							'search_placeholder' => '',
						),
						array(
							'key' => 'field_67093b74b1ef1',
							'label' => 'Background Photo',
							'name' => 'photo',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_66cf654c58593',
										'operator' => '==',
										'value' => 'image',
									),
								),
								array(
									array(
										'field' => 'field_66cf654c58593',
										'operator' => '==',
										'value' => 'image-box',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'uploader' => '',
							'return_format' => 'url',
							'library' => 'all',
							'acfe_thumbnail' => 0,
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'allow_in_bindings' => 0,
							'preview_size' => 'medium',
						),
						array(
							'key' => 'field_67093bc2b1ef2',
							'label' => 'Text Color',
							'name' => 'text_color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_66cf654c58593',
										'operator' => '==',
										'value' => 'image',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'text-white' => 'White',
								'text-white no-overlay' => 'White (No Image Treatment)',
								'text-black' => 'Black',
								'text-black no-overlay' => 'Black (No Image Treatment)',
							),
							'default_value' => 'white',
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'allow_custom' => 0,
							'search_placeholder' => '',
						),
						array(
							'key' => 'field_67093b1779023',
							'label' => '(Column 8/12)',
							'name' => '',
							'aria-label' => '',
							'type' => 'acfe_column',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'columns' => '8/12',
							'endpoint' => 0,
							'allow_in_bindings' => 0,
						),
						array(
							'key' => 'field_67093e0c235a4',
							'label' => 'Content',
							'name' => 'content',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'short',
								'id' => '',
							),
							'default_value' => '',
							'allow_in_bindings' => 0,
							'tabs' => 'visual',
							'toolbar' => 'basic',
							'media_upload' => 0,
							'delay' => 0,
						),
						array(
							'key' => 'field_66b4ec12112b7',
							'label' => 'Module: Calls to Action',
							'name' => 'module-calls-to-action',
							'aria-label' => '',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_66b4eada0859b',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_seamless_style' => 0,
							'acfe_clone_modal' => 0,
							'acfe_clone_modal_close' => 0,
							'acfe_clone_modal_button' => '',
							'acfe_clone_modal_size' => 'large',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
				),
				'layout_670fee792d184' => array(
					'key' => 'layout_670fee792d184',
					'name' => 'event-cards',
					'label' => 'Event Cards',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_670fee8f2d187',
							'label' => 'Module: Event Cards',
							'name' => 'module-event-cards',
							'aria-label' => '',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_670feb7d53e7e',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_seamless_style' => 0,
							'acfe_clone_modal' => 0,
							'acfe_clone_modal_close' => 0,
							'acfe_clone_modal_button' => '',
							'acfe_clone_modal_size' => 'large',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
				),
				'layout_67094ab88c433' => array(
					'key' => 'layout_67094ab88c433',
					'name' => 'facts',
					'label' => 'Facts',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_67094ac08c436',
							'label' => 'Module: Facts',
							'name' => 'module-facts',
							'aria-label' => '',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_6709493c74738',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_seamless_style' => 0,
							'acfe_clone_modal' => 0,
							'acfe_clone_modal_close' => 0,
							'acfe_clone_modal_button' => '',
							'acfe_clone_modal_size' => 'large',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
				),
				'layout_66a12e5d77fc1' => array(
					'key' => 'layout_66a12e5d77fc1',
					'name' => 'goals',
					'label' => 'Goals',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_66a12e6377fc4',
							'label' => 'Module: Goals',
							'name' => 'module-goals',
							'aria-label' => '',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_66a12c567b58d',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_seamless_style' => 0,
							'acfe_clone_modal' => 0,
							'acfe_clone_modal_close' => 0,
							'acfe_clone_modal_button' => '',
							'acfe_clone_modal_size' => 'large',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
				),
				'layout_66d85906551ea' => array(
					'key' => 'layout_66d85906551ea',
					'name' => 'people',
					'label' => 'People',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_66d8590c551ed',
							'label' => 'Module: People',
							'name' => 'module-people',
							'aria-label' => '',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_66d8584c635a6',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_seamless_style' => 0,
							'acfe_clone_modal' => 0,
							'acfe_clone_modal_close' => 0,
							'acfe_clone_modal_button' => '',
							'acfe_clone_modal_size' => 'large',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
				),
				'layout_66f1fd02c3379' => array(
					'key' => 'layout_66f1fd02c3379',
					'name' => 'photo-grid',
					'label' => 'Photo Grid',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_66f1fd0bc337c',
							'label' => 'Module: Photo Grid',
							'name' => 'module-photo-grid',
							'aria-label' => '',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_66f19c5c0cdfc',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_seamless_style' => 0,
							'acfe_clone_modal' => 0,
							'acfe_clone_modal_close' => 0,
							'acfe_clone_modal_button' => '',
							'acfe_clone_modal_size' => 'large',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
				),
				'layout_6655f259ff354' => array(
					'key' => 'layout_6655f259ff354',
					'name' => 'quick-links',
					'label' => 'Quick Links',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_665769647b64c',
							'label' => 'Title',
							'name' => 'quick-links-title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '40',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'allow_in_bindings' => 1,
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_66b4e851445f8',
							'label' => 'Padding',
							'name' => 'padding',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'pad-none' => 'None',
								'pad-side' => 'Side Only',
								'pad-normal' => 'Normal',
								'pad-tall' => 'Tall',
							),
							'default_value' => 'pad-normal',
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'allow_custom' => 0,
							'search_placeholder' => '',
						),
						array(
							'key' => 'field_66e48e0ba27b7',
							'label' => 'Color',
							'name' => 'color',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'tan' => 'Tan',
								'white' => 'White',
							),
							'default_value' => 'white',
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'allow_custom' => 0,
							'search_placeholder' => '',
						),
						array(
							'key' => 'field_6655f33aff35b',
							'label' => 'Rows',
							'name' => 'rows',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_repeater_stylised_button' => 0,
							'layout' => 'block',
							'min' => 1,
							'max' => 0,
							'collapsed' => 'field_6655f278ff357',
							'button_label' => 'Add Row',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_6655f278ff357',
									'label' => 'Title',
									'name' => 'title',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '40',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_6655f33aff35b',
								),
								array(
									'key' => 'field_6655f2b1ff359',
									'label' => 'Link Text',
									'name' => 'link-text',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '30',
										'class' => '',
										'id' => '',
									),
									'default_value' => 'Learn more',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_6655f33aff35b',
								),
								array(
									'key' => 'field_6655f2c3ff35a',
									'label' => 'Link URL',
									'name' => 'link',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '30',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_6655f33aff35b',
								),
								array(
									'key' => 'field_6655f264ff356',
									'label' => 'Photo',
									'name' => 'photo',
									'aria-label' => '',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '30',
										'class' => '',
										'id' => '',
									),
									'uploader' => '',
									'return_format' => 'url',
									'acfe_thumbnail' => 0,
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'preview_size' => 'medium',
									'library' => 'all',
									'parent_repeater' => 'field_6655f33aff35b',
								),
								array(
									'key' => 'field_6655f282ff358',
									'label' => 'Content',
									'name' => 'content',
									'aria-label' => '',
									'type' => 'textarea',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '70',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'acfe_textarea_code' => 0,
									'maxlength' => '',
									'rows' => 4,
									'placeholder' => '',
									'new_lines' => '',
									'parent_repeater' => 'field_6655f33aff35b',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
				),
				'layout_665dd2aadac54' => array(
					'key' => 'layout_665dd2aadac54',
					'name' => 'quotes',
					'label' => 'Quotes (Multiple)',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_665dd3b2dac56',
							'label' => 'Module: Quotes (Multiple)',
							'name' => 'module-quotes-multiple',
							'aria-label' => '',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_669a831999312',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_seamless_style' => 0,
							'acfe_clone_modal' => 0,
							'acfe_clone_modal_close' => 0,
							'acfe_clone_modal_button' => '',
							'acfe_clone_modal_size' => 'large',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
				),
				'layout_6660b2886f8d0' => array(
					'key' => 'layout_6660b2886f8d0',
					'name' => 'quote-large',
					'label' => 'Quote (Large)',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_669a7edb9cf3f',
							'label' => 'Module: Quote (Large)',
							'name' => 'module-quote-large',
							'aria-label' => '',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_669a7e1351987',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_seamless_style' => 0,
							'acfe_clone_modal' => 0,
							'acfe_clone_modal_close' => 0,
							'acfe_clone_modal_button' => '',
							'acfe_clone_modal_size' => 'large',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
				),
				'layout_667c260d434e1' => array(
					'key' => 'layout_667c260d434e1',
					'name' => 'stats',
					'label' => 'Statistics',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_667c2633434e7',
							'label' => 'Module: Statistics',
							'name' => 'module-statistics',
							'aria-label' => '',
							'type' => 'clone',
							'instructions' => 'Small title above the main title.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_669a810de362a',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_seamless_style' => 0,
							'acfe_clone_modal' => 0,
							'acfe_clone_modal_close' => 0,
							'acfe_clone_modal_button' => '',
							'acfe_clone_modal_size' => 'large',
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
				),
				'layout_669873dfebda6' => array(
					'key' => 'layout_669873dfebda6',
					'name' => 'tabs',
					'label' => 'Tabs',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_669873f8ebda8',
							'label' => 'Tab',
							'name' => 'tabs',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_repeater_stylised_button' => 0,
							'layout' => 'block',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Add Tab',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_66987476ebda9',
									'label' => 'Label',
									'name' => 'label',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_669873f8ebda8',
								),
								array(
									'key' => 'field_66987489ebdaa',
									'label' => 'Tab Components',
									'name' => 'tab-components',
									'aria-label' => '',
									'type' => 'clone',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'clone' => array(
										0 => 'field_664e26e508e2c',
									),
									'display' => 'seamless',
									'layout' => 'block',
									'prefix_label' => 0,
									'prefix_name' => 0,
									'acfe_seamless_style' => 0,
									'acfe_clone_modal' => 0,
									'acfe_clone_modal_close' => 0,
									'acfe_clone_modal_button' => '',
									'acfe_clone_modal_size' => 'large',
									'parent_repeater' => 'field_669873f8ebda8',
								),
							),
						),
					),
					'min' => '',
					'max' => '',
					'acfe_flexible_render_template' => false,
					'acfe_flexible_render_style' => false,
					'acfe_flexible_render_script' => false,
					'acfe_flexible_thumbnail' => false,
					'acfe_flexible_settings' => false,
					'acfe_flexible_settings_size' => 'medium',
					'acfe_flexible_modal_edit_size' => false,
					'acfe_flexible_category' => false,
				),
			),
			'min' => '',
			'max' => '',
			'button_label' => 'Add Component',
			'acfe_flexible_stylised_button' => false,
			'acfe_flexible_hide_empty_message' => false,
			'acfe_flexible_empty_message' => '',
			'acfe_flexible_layouts_templates' => false,
			'acfe_flexible_layouts_previews' => false,
			'acfe_flexible_layouts_placeholder' => false,
			'acfe_flexible_layouts_thumbnails' => false,
			'acfe_flexible_layouts_settings' => false,
			'acfe_flexible_async' => array(
			),
			'acfe_flexible_add_actions' => array(
			),
			'acfe_flexible_remove_button' => array(
			),
			'acfe_flexible_layouts_state' => false,
			'acfe_flexible_modal_edit' => array(
				'acfe_flexible_modal_edit_enabled' => false,
				'acfe_flexible_modal_edit_size' => 'large',
			),
			'acfe_flexible_modal' => array(
				'acfe_flexible_modal_enabled' => false,
				'acfe_flexible_modal_title' => false,
				'acfe_flexible_modal_size' => 'full',
				'acfe_flexible_modal_col' => '4',
				'acfe_flexible_modal_categories' => false,
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'area',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => array(
		0 => 'block_editor',
		1 => 'the_content',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1733340188,
));

endif;