<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_66548984eb761',
	'title' => 'Site Options',
	'fields' => array(
		array(
			'key' => 'field_668582baed050',
			'label' => 'Header',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_6685832a1e37a',
			'label' => 'Header Menu',
			'name' => 'menu',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 0,
			'layout' => 'block',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => 'field_6685833f1e37b',
			'button_label' => 'Add Main Menu Item',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_6685833f1e37b',
					'label' => 'Label',
					'name' => 'label',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6685832a1e37a',
				),
				array(
					'key' => 'field_668583d51e37d',
					'label' => 'Link',
					'name' => 'link',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '60',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6685832a1e37a',
				),
				array(
					'key' => 'field_66858624a3e05',
					'label' => 'Submenu Modules',
					'name' => 'submenu-modules',
					'aria-label' => '',
					'type' => 'flexible_content',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_flexible_advanced' => 0,
					'layouts' => array(
						'layout_6697e2dc1b301' => array(
							'key' => 'layout_6697e2dc1b301',
							'name' => 'submenu',
							'label' => 'Submenu',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_668fdbd298dfb',
									'label' => 'Title',
									'name' => 'title',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '40',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_6685862ea3e06',
									'label' => 'Menu',
									'name' => 'nav-menu',
									'aria-label' => '',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '60',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										0 => '- no menu -',
										'about-engage' => 'About - Engage',
										'about-history' => 'About - History',
										'about-main' => 'About - Main',
										'about-support' => 'About - Support',
										'academics-experiential-learning' => 'Academics - Experiential Learning',
										'academics-library' => 'Academics - Library',
										'academics-overview' => 'Academics - Overview',
										'academics-registrar' => 'Academics - Registrar',
										'admission-accepted-students' => 'Admission - Accepted Students',
										'admission-apply' => 'Admission - Apply',
										'admission-financial-aid' => 'Admission - Financial Aid',
										'admission-overview' => 'Admission - Overview',
										'admission-visit' => 'Admission - Visit',
										'apply-now' => 'Apply Now',
										'areas-of-study-nav' => 'Areas of Study Nav',
										'centers-and-resources' => 'Centers and Resources',
										'community-resources' => 'Community Resources',
										'donors' => 'Donors',
										'financial-aid-short' => 'Financial Aid Short',
										'footer-faculty' => 'Footer - Faculty',
										'footer-overview' => 'Footer - Overview',
										'footer-students' => 'Footer - Students',
										'for-parents' => 'for parents',
										'give-forever-ripon' => 'Give - Forever Ripon',
										'give-how-to-give' => 'Give - How to Give',
										'give-infrastructure' => 'Give - Infrastructure',
										'header-main' => 'Header - Main',
										'home-passions' => 'Home - Passions',
										'impact-of-giving' => 'Impact of Giving',
										'international-students' => 'International Students',
										'maps' => 'Maps',
										'news-and-events' => 'News and Events',
										'student-life-club-activities' => 'Student Life - Club &amp; Activities',
										'student-life-diversity-inclusion' => 'Student Life - Diversity &amp; Inclusion',
										'student-life-housing' => 'Student Life - Housing',
										'student-life-main' => 'Student Life - Main',
										'student-life-overview' => 'Student Life - Overview',
										'student-life-services' => 'Student Life - Services',
										'title-academics' => 'Title - Academics',
										'transfer-to-ripon' => 'Transfer To Ripon',
										'where-to-give' => 'Where to GIve',
									),
									'default_value' => false,
									'return_format' => 'value',
									'multiple' => 0,
									'allow_null' => 0,
									'ui' => 0,
									'ajax' => 0,
									'placeholder' => '',
									'allow_custom' => 0,
									'search_placeholder' => '',
									'create_options' => 0,
									'save_options' => 0,
								),
							),
							'min' => '',
							'max' => '',
							'acfe_flexible_render_template' => false,
							'acfe_flexible_render_style' => false,
							'acfe_flexible_render_script' => false,
							'acfe_flexible_thumbnail' => false,
							'acfe_flexible_settings' => false,
							'acfe_flexible_settings_size' => 'medium',
							'acfe_flexible_modal_edit_size' => false,
							'acfe_flexible_category' => false,
						),
						'layout_6697e37b53719' => array(
							'key' => 'layout_6697e37b53719',
							'name' => 'content-area',
							'label' => 'Content',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_6697e3a25371c',
									'label' => 'Title',
									'name' => 'title',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
								array(
									'key' => 'field_6697e3865371b',
									'label' => 'Content',
									'name' => 'content',
									'aria-label' => '',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 0,
								),
							),
							'min' => '',
							'max' => '',
							'acfe_flexible_render_template' => false,
							'acfe_flexible_render_style' => false,
							'acfe_flexible_render_script' => false,
							'acfe_flexible_thumbnail' => false,
							'acfe_flexible_settings' => false,
							'acfe_flexible_settings_size' => 'medium',
							'acfe_flexible_modal_edit_size' => false,
							'acfe_flexible_category' => false,
						),
						'layout_669816b37ef31' => array(
							'key' => 'layout_669816b37ef31',
							'name' => 'event',
							'label' => 'Featured Event',
							'display' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_669816c07ef33',
									'label' => 'Event',
									'name' => 'event',
									'aria-label' => '',
									'type' => 'post_object',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'post_type' => '',
									'post_status' => '',
									'taxonomy' => '',
									'return_format' => 'object',
									'multiple' => 0,
									'save_custom' => 0,
									'save_post_status' => 'publish',
									'acfe_bidirectional' => array(
										'acfe_bidirectional_enabled' => '0',
									),
									'allow_null' => 0,
									'bidirectional' => 0,
									'ui' => 1,
									'bidirectional_target' => array(
									),
									'save_post_type' => '',
								),
							),
							'min' => '',
							'max' => '',
							'acfe_flexible_render_template' => false,
							'acfe_flexible_render_style' => false,
							'acfe_flexible_render_script' => false,
							'acfe_flexible_thumbnail' => false,
							'acfe_flexible_settings' => false,
							'acfe_flexible_settings_size' => 'medium',
							'acfe_flexible_modal_edit_size' => false,
							'acfe_flexible_category' => false,
						),
					),
					'min' => '',
					'max' => '',
					'button_label' => 'Add Row',
					'acfe_flexible_stylised_button' => false,
					'acfe_flexible_hide_empty_message' => false,
					'acfe_flexible_empty_message' => '',
					'acfe_flexible_layouts_templates' => false,
					'acfe_flexible_layouts_previews' => false,
					'acfe_flexible_layouts_placeholder' => false,
					'acfe_flexible_layouts_thumbnails' => false,
					'acfe_flexible_layouts_settings' => false,
					'acfe_flexible_async' => array(
					),
					'acfe_flexible_add_actions' => array(
					),
					'acfe_flexible_remove_button' => array(
					),
					'acfe_flexible_layouts_state' => false,
					'acfe_flexible_modal_edit' => array(
						'acfe_flexible_modal_edit_enabled' => false,
						'acfe_flexible_modal_edit_size' => 'large',
					),
					'acfe_flexible_modal' => array(
						'acfe_flexible_modal_enabled' => false,
						'acfe_flexible_modal_title' => false,
						'acfe_flexible_modal_size' => 'full',
						'acfe_flexible_modal_col' => '4',
						'acfe_flexible_modal_categories' => false,
					),
					'parent_repeater' => 'field_6685832a1e37a',
				),
			),
		),
		array(
			'key' => 'field_66858db5787f7',
			'label' => 'Header Scripts',
			'name' => 'header_scripts',
			'aria-label' => '',
			'type' => 'acfe_code_editor',
			'instructions' => 'Scripts injected at the end of the <strong>head</strong> tag.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'mode' => 'text/html',
			'lines' => 1,
			'indent_unit' => 4,
			'maxlength' => '',
			'rows' => 10,
			'max_rows' => '',
			'return_format' => array(
			),
		),
		array(
			'key' => 'field_66858e77f1cb2',
			'label' => 'Body Scripts',
			'name' => 'body_scripts',
			'aria-label' => '',
			'type' => 'acfe_code_editor',
			'instructions' => 'Scripts injected at the top of the page, just after the <strong>body</strong> tag.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'mode' => 'text/html',
			'lines' => 1,
			'indent_unit' => 4,
			'maxlength' => '',
			'rows' => 10,
			'max_rows' => '',
			'return_format' => array(
			),
		),
		array(
			'key' => 'field_6685829aed04f',
			'label' => 'Footer',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_665489846056f',
			'label' => 'Footer Address',
			'name' => 'address',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_668582ceed051',
			'label' => 'Footer Scripts',
			'name' => 'footer_scripts',
			'aria-label' => '',
			'type' => 'acfe_code_editor',
			'instructions' => 'Injected just before the close of the <strong>body</strong> tag.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'mode' => 'text/html',
			'lines' => 1,
			'indent_unit' => 4,
			'maxlength' => '',
			'rows' => 14,
			'max_rows' => '',
			'return_format' => array(
			),
		),
		array(
			'key' => 'field_66548ace3177d',
			'label' => 'Social Icons',
			'name' => 'social',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '100',
				'class' => '',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 0,
			'layout' => 'table',
			'pagination' => 0,
			'min' => 2,
			'max' => 0,
			'collapsed' => 'field_66548b041cd9c',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_66548b041cd9c',
					'label' => 'Network',
					'name' => 'network',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '35',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'facebook' => 'Facebook',
						'instagram' => 'Instagram',
						'linkedin' => 'LinkedIn',
						'x' => 'X (Twitter)',
						'youtube' => 'YouTube',
						'zeemee' => 'Zeemee',
					),
					'default_value' => 'facebook',
					'return_format' => 'array',
					'multiple' => 0,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'allow_custom' => 0,
					'search_placeholder' => '',
					'create_options' => 0,
					'save_options' => 0,
					'parent_repeater' => 'field_66548ace3177d',
				),
				array(
					'key' => 'field_66548bbe1cd9d',
					'label' => 'Link',
					'name' => 'link',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '65',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'parent_repeater' => 'field_66548ace3177d',
				),
			),
		),
		array(
			'key' => 'field_673b4c5dcec69',
			'label' => 'Events',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_673b4c6bcec6a',
			'label' => 'Event Retention',
			'name' => 'event-retention',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => 'Set the number of days that events are kept after they\'ve past.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 365,
			'min' => '',
			'max' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'step' => 1,
			'prepend' => '',
			'append' => 'days',
		),
		array(
			'key' => 'field_68c1c9a9aa61d',
			'label' => 'Guides',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_68c1c9b4aa61e',
			'label' => 'All Guides Page',
			'name' => 'all-guides',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'page',
			),
			'post_status' => array(
				0 => 'publish',
			),
			'taxonomy' => '',
			'return_format' => 'object',
			'multiple' => 0,
			'save_custom' => 0,
			'save_post_status' => 'publish',
			'acfe_bidirectional' => array(
				'acfe_bidirectional_enabled' => '0',
			),
			'allow_null' => 0,
			'allow_in_bindings' => 0,
			'bidirectional' => 0,
			'ui' => 1,
			'bidirectional_target' => array(
			),
			'save_post_type' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'site-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1757530599,
));

endif;