<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_6a6a4582cdbc6',
	'title' => 'Import Events',
	'fields' => array(
		array(
			'key' => 'field_6a737ca7dece4',
			'label' => 'About This Tool',
			'name' => '',
			'aria-label' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Use this interface to set up the importing of events from <strong>Google Calender(s)</strong>. You\'re able to add multiple calendar IDs, and the tool will reach out to Google Calendar API and pull a complete list of all the events in it, importing them into the events section of the website. You can also enable/disable the job if you need to have maintenance done to the Google Calendars and don\'t want incomplete events coming through to the site.

<h4>Instructions</h4>
Your calendar needs to be publicly available - to do so, visit your calendar in a browser on a computer, mouseover the calendar you\'d like to share in the left column, and click the three dot icon, then choose \'Settings & Sharing\'. Under \'Access permissions for events\', check the \'Make available to public\' option. Scroll down to the \'Integrate Calendar\' section, and get the Calendar ID from there. Make sure to save the settings so your calendar is public.',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_6a737c66dece2',
			'label' => 'Calendars',
			'name' => 'calendars',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 0,
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_6a737c86dece3',
					'label' => 'Calendar ID',
					'name' => 'calid',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'See instructions above to get this.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6a737c66dece2',
				),
				array(
					'key' => 'field_6a737defc5be9',
					'label' => 'Activation',
					'name' => 'active',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => 'Enable/disable each calendar import job.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '19',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'allow_in_bindings' => 0,
					'ui_on_text' => 'Enabled',
					'ui_off_text' => 'Disabled',
					'ui' => 1,
					'parent_repeater' => 'field_6a737c66dece2',
				),
				array(
					'key' => 'field_6a8f2f874a4cf',
					'label' => 'Category',
					'name' => 'category',
					'aria-label' => '',
					'type' => 'acfe_taxonomy_terms',
					'instructions' => 'Select the categories to which each calendars events should be added.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '30',
						'class' => '',
						'id' => '',
					),
					'taxonomy' => array(
						0 => 'event_cat',
					),
					'allow_terms' => '',
					'allow_level' => '',
					'field_type' => 'select',
					'default_value' => array(
					),
					'return_format' => 'object',
					'ui' => 1,
					'allow_null' => 0,
					'placeholder' => '',
					'multiple' => 1,
					'ajax' => 0,
					'save_terms' => 0,
					'load_terms' => 0,
					'allow_in_bindings' => 0,
					'choices' => array(
					),
					'search_placeholder' => '',
					'layout' => '',
					'toggle' => 0,
					'allow_custom' => 0,
					'other_choice' => 0,
					'parent_repeater' => 'field_6a737c66dece2',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'import-events',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
	'allow_ai_access' => false,
	'ai_description' => '',
	'acfe' => array(
		'autosync' => array(
			0 => 'php',
		),
	),
	'modified' => 1787769487,
));

endif;